- The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and 
- most other data science and scientific Python packages.



In [3]:
import numpy as np

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [5]:
import numpy as np
a = np.array([5,5,5])
a

array([5, 5, 5])

In [6]:
type(a)

numpy.ndarray

In [10]:
len(a)

3

In [11]:
a[0]

5

In [12]:
a[:]

array([5, 5, 5])

In [8]:
# 2-D arrays (lists of lists)

b = np.array([ [5,5,5],
             [5,5,5],
             [5,5,5] ])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### One(single) dimensional array is also called a vector
### There is no differene between row or column vector

### Two dimensional array is called a matrix

### Three or higher dimensional arrays use a term tensor

### Dimensions are also called axis

In [13]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
b = np.zeros(2)
b

array([0., 0.])

In [16]:
c = np.ones(3)
c

array([1., 1., 1.])

In [18]:
# create an empty array with 2 elements

d = np.empty(3)
d

array([1., 1., 1.])

In [19]:
# with range of elements

e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [20]:
f = np.arange(2, 20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
# 2 to 19 with interval of 2

g = np.arange(2, 20, 2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# linearly spaced arrays
# shall print all elements between first two arguments but with at distance of num=5 

h = np.linspace(0, 15, num=5)
h

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [27]:
# specific data types in arrays

i = np.ones(5, dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [28]:
j = np.ones(3, dtype=np.float64)
j

array([1., 1., 1.])

# Create 2-D arrays

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Create 3-D arrays

In [33]:
m = np.arange(24).reshape(2,3,4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# More numpy array operations

In [34]:
import numpy as np

- creating an array using numpy array

In [35]:
# 1D array

food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [36]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [37]:
type(price)

numpy.ndarray

In [38]:
len(price)

3

In [39]:
price[2]

5

In [40]:
price.mean()

5.0

In [41]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [44]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [46]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [48]:
# specific interval
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [49]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [52]:
# linespace
np.linspace(0, 100, num=5)

array([  0.,  25.,  50.,  75., 100.])

In [53]:
# specify your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [55]:
np.ones(20, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Array functions

In [57]:
# it will convert integers to float because array is homog

a = np.array([10, 12, 15, 5.2, 6.3, 98, 100])
a

array([ 10. ,  12. ,  15. ,   5.2,   6.3,  98. , 100. ])

In [58]:
a.sort()
a

array([  5.2,   6.3,  10. ,  12. ,  15. ,  98. , 100. ])

In [59]:
b = np.array([10.2, 3.4, 53.6,200])
b

array([ 10.2,   3.4,  53.6, 200. ])

In [63]:
c = np.concatenate((a,b))
c

array([  5.2,   6.3,  10. ,  12. ,  15. ,  98. , 100. ,  10.2,   3.4,
        53.6, 200. ])

In [65]:
c.sort()
c

array([  3.4,   5.2,   6.3,  10. ,  10.2,  12. ,  15. ,  53.6,  98. ,
       100. , 200. ])

# 2-D arrays

In [68]:
x = np.array([[1,2], [5,4]])
x

array([[1, 2],
       [5, 4]])

In [69]:
y = np.array([[6,7],[7,8]])
y

array([[6, 7],
       [7, 8]])

In [70]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [71]:
np.concatenate((x,y), axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [81]:
# 3-D array or tensor

a = np.array([[[0,1,2,3],
             [4,5,6,7]],
            
            [[0,1,2,3],
             [4,5,6,7]],
            
            [[0,1,2,3],
             [4,5,6,7]]])

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [77]:
# to find number of dimensions

a.ndim

3

In [79]:
b = np.array([[5,6,7],
             [8,9,10],
             [10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [80]:
b.ndim

2

In [84]:
# number of elements = size
a.size

24

In [83]:
b.size

9

In [87]:
# shape (this one is three-dimensional with 2x4 cells)

a.shape

(3, 2, 4)

In [86]:
b.shape

(3, 3)

In [91]:
# reshape an array (1D to 2D)

a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## Convert 1D to 2D

In [101]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# 1D
a.shape

(9,)

In [104]:
# row conversion

b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [106]:
# 2D
b.shape

(1, 9)

In [108]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [110]:
# 2 D
c.shape

(9, 1)

In [94]:
# multiply by a number

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
a+6

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
a*6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48])

In [97]:
a.sum()

36

In [98]:
a.mean()

4.0